version: '3'
services:
  db:
    image: ghcr.io/suptar21/projectii-database:master
    container_name: Studart-database
    networks:
      - database_myproduct-network
    restart: always
    volumes:
      - ./data-sys:/var/lib/mysql
      - ./conf-sys/my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    env_file:
      - ./.env
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Studart-db-admin
    links:
      - db
    restart: always
    ports:
      - 8081:80
      
networks:
  default:
    name: database_myproduct-network
