
version: '3'
services:
  database:
    image: ghcr.io/suptar21/projectii-database:master
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    env_file:
      - ./.env
    ports:
      - "3306:3306"
      
  database-admin:
    image: phpmyadmin/phpmyadmin
    container_name: studart-database-admin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

networks:
  default:
    name: studart-database-network
