version: '3'
services:
  database:
    image: ghcr.io/suptar21/projectii-database:master
    container_name: studart-database
    restart: always
    volumes:
      - ./data-sys:/var/lib/mysql
      - ./conf-sys/my.cnf:/etc/my.cnf
      
  database-admin:
    image: phpmyadmin/phpmyadmin
    container_name: studart-database-admin
    restart: always
    ports:
      - 8081:80
      
networks:
  default:
    external:
      name: studart-database-network
 
