version: '3'
services:
  db:
    image: ghcr.io/suptar21/projectii-database:master
    container_name: Studart-database
    networks:
      - studart-network
    restart: always
    volumes:
      - ./data-sys:/var/lib/mysql
      - ./conf-sys/my.cnf:/etc/my.cnf
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Studart-db-admin
    links:
      - db
    restart: always
    ports:
      - 8081:80
      
networks:
  default:
    external:
      name: studart-database-network
 
